name: pay_day_manager
version: 1.0.0+1
publish_to: none
description: PayDay Managers App will be developed following SCRUM guidelines in an incremental, iterative manner in a time-boxed sprint of two weeks.
environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: ^4.0.6
  flutter_screenutil: 5.7.0
  # firebase_messaging: ^14.2.2
  # flutter_local_notifications: ^13.0.0
  # firebase_core: ^2.5.0
  table_calendar: ^3.0.9
  intl: ^0.18.0
  flutter_svg: ^2.0.0+1
  shared_preferences: ^2.0.17
  custom_pop_up_menu: 1.2.4
  auto_size_text: 3.0.0
  flutter_easyloading: ^3.0.5
  dropdown_button2: 1.9.2
  stylish_bottom_bar: ^1.0.1
  path_provider: ^2.0.10
  sqflite: ^2.2.8+4
  cached_network_image: ^3.2.3
  image_picker: ^1.0.4
  loadmore: ^2.1.0
  order_tracker_zen: ^1.0.0+4
  flutter_otp_text_field: ^1.1.1
  firebase_messaging: ^14.7.1
  firebase_core: ^2.19.0
  flutter_local_notifications: ^16.1.0
  permission_handler: ^11.0.1

  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  build_runner: ^2.3.3
  flutter_lints: 2.0.1
 

dev_dependencies:
  json_serializable: ^6.6.2
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/assets_svg/
    - assets/png_assets/
    - assets/png_assets/3.0x/
    - assets/png_assets/2.0x/
    - assets/png_assets/bg_assets/
    - assets/lottie_images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font_styles/Poppins/Poppins-Regular.ttf
        - asset: assets/font_styles/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font_styles/Poppins/Poppins-Bold.ttf
          weight: 700

  #        - asset: assets/font_styles/Poppins/Poppins-Bold.ttf
  #          weight: 600
  #        - asset: assets/font_styles/Poppins/Poppins-SemiBold.ttf
  #          weight: 900
  uses-material-design: true

