class ConstAsset {
  static const logoSVG = "assets/assets_svg/pay_day_manager_logo.svg";
  static const addBiometricLogoSVG = "assets/png_assets/logo_png.png";
  static const addBiometricBGLogoSVG = "assets/png_assets/bg_image.png";
  static const refreshSVG = "assets/assets_svg/refresh.svg";
  static const checkBoxSVG = "assets/assets_svg/check_box.svg";
  static const eyeSVG = "assets/assets_svg/icon_eye.svg";
  static const calendarPng = "assets/png_assets/calendar.png";
  static const faceIdPng = "assets/png_assets/faceid.png";
  static const fingerprintPng = "assets/png_assets/fingerprint.png";
  static const fingerprintSVG = "assets/assets_svg/fingerprint.svg";
  static const noInternetSVG = "assets/assets_svg/no_internet_connection_svg.svg";
  static const calendarSVG = "assets/assets_svg/calendar_icon.svg";
  static const myProfileSVG = "assets/assets_svg/icon_my_profile.svg";
  static const dailyStatusSVG = "assets/assets_svg/icon_daily_status.svg";
  static const managerAccountSVG = "assets/assets_svg/icon_manager_account.svg";
  static const employeeProfileSVG = "assets/assets_svg/icon_employee_profile.svg";
  static const supportSVG = "assets/assets_svg/icon_support.svg";
  static const logoutSVG = "assets/assets_svg/icon_logout.svg";
  static const downArrowSVG = "assets/assets_svg/icon_down_arrow.svg";
  static const rightArrowSVG = "assets/assets_svg/icon_right_arrow.svg";
  static const bellIconSVG = "assets/assets_svg/icon_bell.svg";
  static const envelopeIconSVG = "assets/assets_svg/envelope.svg";
  static const hamburgerIconSVG = "assets/assets_svg/hamburger_icon_svg.svg";
  static const dollarIconSVG = "assets/assets_svg/icon_dollar_svg.svg";
  // static const backgroundSVG = "assets/assets_svg/icon_dollar_svg.svg";
  static const backgroundSVG = "assets/assets_svg/back_ground.svg";
  static const internalServerError = "assets/assets_svg/information_error.svg";
}
